# Custom Language File for Launcher Customizer

[ejs.app]
title = "PixelmonMasters"

[ejs.landing]
mediaGitHubURL = "https://github.com/pixelmon-masters/PixelmonMasters"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/gKG9CCsS"

[ejs.settings]
sourceGithubLink = "https://github.com/pixelmon-masters/PixelmonMasters"
supportLink = "https://github.com/pixelmon-masters/PixelmonMasters/issues"

[ejs.welcome]
welcomeHeader = "welcome To PixelmonMasters"
welcomeDescription = "해당 런처는 '아이곰(discord: babybear7)'에 의해 제작되었습니다."
welcomeDescCTA = "몇번만 더 클릭하시면 됩니다!"
